package alex.common.voice;

import java.util.Random;

final public class PositivePhrases {
    private static final String[] POSITIVE_PHRASES = {"All Right!", "Exactly right", "Excellent!", "Exceptional", "Fabulous!", "Fantastic!", "Sensational!", "Wonderful!", "Outstanding!", "That's it!", "Just right!", "Unbelievable", "Way to go!", "Simply superb", "Stupendous!", "Magnificent", "Marvelous!", "First class job", "First class work", "Good for you!", "That's great", "Good going!", "Good thinking", "Right on!", "Better than ever!", "I'm impressed!", "You're one of a kind", "You've got it now.", "You've mastered it!", "What an improvement!", "You always amaze me", "You are fantastic", "You are learning a lot", "You are learning fast", "You are so good", "You did it!", "You did that very well", "You don't miss a thing", "You got it right!", "You hit the target", "I'm very proud of you", "Keep up the great work!", "Nothing can stop you now", "Now you've figured it out", "You make it look easy", "You haven't missed a thing", "You did that all by yourself", "That's really nice work!", "You're doing beautifully!", "You are very good at that", "That's the way to do it", "It's perfect!", "Nice going!", "That's right!", "Well done", "I'm speechless!", "Great work", "Keep it up!", "You got it!", "Not bad at all!", "That's the way!", "Now you have it", "I knew you could do it!", "Great improvement!", "That's it exactly", "That's the best ever", "That's the way to do it", "Couldn't have done it better myself", "Tremendous job", "You're doing well", "You're learning fast", "That's the right way to do it", "You're doing a great job", "Your studying really paid off", "You must have been practicing", "You're on the right track now", "You're getting better every day", "I've never seen anyone do it better", "It looks like you've put a lot of work into this", "Now that's what I call a great job", "That's the right way to do it", "You certainly did well today."};

    public static String getRandom(Random random) {
        return POSITIVE_PHRASES[random.nextInt(PositivePhrases.POSITIVE_PHRASES.length)];
    }
}